manifest:
  self:
    path: my-manifest
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: main
      path: zephyr
    - name: hal_nordic
      url: https://github.com/zephyrproject-rtos/hal_nordic
      revision: main
      path: modules/hal/nordic